### ISSUE TITLE
Text shifts down

### ISSUE THREAD

**Issue by bsherms** [bsherms/kraken-good-accessibility#1]
Hi @thomasjbradley 
When I run my code through Markbot I receive a 23% difference error for the print screenshot. 
It looks like all of the text shifts down a touch and I'm not sure why that would occur. 

Let me know if you have any suggestions.
Thank you!

**Comment by thomasjbradley** [comment]
It matches perfectly for me—did you figure it out?

**Comment by bsherms** [comment]
Weird... no. I will see if I need to update anything and try running it through again.

**Comment by bsherms** [comment]
Updated creative cloud and macOS, resubmitted and it worked!
